FROM ubuntu:16.04

WORKDIR /mydir
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt install -y nodejs && \
    apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/* 

COPY . .
RUN npm install

EXPOSE 8000
CMD FRONT_URL=http://localhost:5001 npm start

# docker build -t bed .
# docker run --rm -p 8000:8000 -v $(pwd)/backend-example-docker/logs.txt:/mydir/logs.txt bed
